//
//  DynamiteRoute.swift
//  CodeEdit
//

import Foundation

/// A workspace-relative navigation target in the `dynamite://` URL scheme.
///
/// Routes are parsed and generated by `Router` and are used for cross-deep-links between Product
/// Studio and Ground Control. All routes resolve within a single workspace (cross-workspace routing
/// is deferred).
///
/// URL format:
/// ```
/// dynamite://node/<node-id>
/// dynamite://surface/<surface-id>
/// dynamite://code?path=<repo-rel-path>[&line=<n>][&symbol=<name>]
/// dynamite://context?path=<repo-rel-path>
/// dynamite://mode/<studio|ground-control>
/// ```
enum DynamiteRoute: Equatable {
    // MARK: - Product Studio routes

    /// Focus a product-graph node in Product Studio.
    case node(id: String)

    /// Open a named Product Studio surface by its registered identifier.
    case surface(id: String)

    // MARK: - Ground Control routes

    /// Open a workspace-relative file path in Ground Control at an optional line and/or symbol.
    ///
    /// If the path resolves to a stale anchor, `Router` attempts re-resolution via the
    /// `LinkIndex` content-hash anchor (ADR-0001 §2). Unresolved paths show a "file not found" notice.
    case code(path: String, line: Int?, symbol: String?)

    /// Surface the product context for a workspace-relative file.
    ///
    /// Opens Product Studio if not already in Ground Control; shows the Ground Control inspector
    /// panel otherwise.
    case context(path: String)

    // MARK: - Mode route

    /// Switch the current window to the specified view mode.
    case mode(ViewMode)
}
